import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import { notoSans } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={`${notoSans.className} antialiased h-full`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
